---
services:
  database:
    container_name: ocv-postgres
    image: postgres:16.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes: 
      - ocv-postgres:/var/lib/postgresql/data
      - ./database/sql/ddl/:/docker-entrypoint-initdb.d/
    networks:
      - ocv-network
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4:8.1
    container_name: ocv-pgadmin4
    ports:
      - '8888:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - civic-voice-pgadmin4:/var/lib/pgadmin
    networks:
      - ocv-network
    restart: unless-stopped

networks:
  ocv-network:
    external: true
volumes:
  ocv-postgres:
  civic-voice-pgadmin4:
